// const favorites: Favorites = [
//   {
//     title: 'xuexi13131313141414',
//     desc: '学习资源',
//     children: [
//       {
//         title: 'bilibili',
//         desc: '弹幕视频平台asdasgasgasfadasfqweqwt2134126512451ewstgwetwesgdgwqetqwtrqwtr',
//         url: 'https://www.bilibili.com/',
//       },
//     ],
//   },
//   {
//     title: 'tech',
//     desc: '技术社区',
//     children: [
//       {
//         title: 'juejin',
//         desc: '技术社区12easfasfasggasgasdasfggasgqw4r5214521sdgsdgqaedrqwrqwtqwt',
//         url: 'https://juejin.cn',
//       },
//       {
//         title: 'Stack Overflow',
//         desc: '开发者平台sadfgfsgasgasagsgagasfgasfasgasgasgasdasdqwrqwtqw3214215125asafgsgas',
//         url: 'https://stackoverflow.com',
//       },
//     ],
//   },
//   {
//     title: 'programing',
//     desc: '编程资源safasgasgasgasdas',
//     children: [
//       {
//         title: 'frontend',
//         desc: '前端资源fgasgasgasgags',
//         children: [
//           {
//             title: 'MDN docs',
//             desc: '最权威的前端技术文档dasgfasgasgasdasdfasfasgas',
//             url: 'https://developer.mozilla.org',
//           },
//           {
//             title: 'Ant Design Vue',
//             desc: '阿里组件库',
//             url: 'https://antdv.com',
//           },
//           {
//             title: 'Vue.js',
//             desc: 'Vue官方文档',
//             url: 'https://vuejs.org',
//           },
//         ],
//       },
//     ],
//   },
// ]

const favorites = [
  {
    children: [
      {
        children: [
          {
            children: [
              {
                children: [
                  {
                    dateAdded: 1666100795975,
                    id: '67',
                    index: 0,
                    parentId: '66',
                    title: 'MDN Web Docs',
                    url: 'https://developer.mozilla.org/zh-CN/',
                    key: '0-0-0-0-0-0',
                  },
                  {
                    dateAdded: 1672929907716,
                    id: '68',
                    index: 1,
                    parentId: '66',
                    title: '中文文档 | anime.js',
                    url: 'http://blog.fer-link.com/demo/20220915111146/index2.html',
                    key: '0-0-0-0-0-1',
                  },
                  {
                    dateAdded: 1670237648898,
                    id: '69',
                    index: 2,
                    parentId: '66',
                    title: 'VuePress中文网',
                    url: 'http://caibaojian.com/vuepress/',
                    key: '0-0-0-0-0-2',
                  },
                  {
                    dateAdded: 1669628711757,
                    id: '70',
                    index: 3,
                    parentId: '66',
                    title: 'Free Frontend',
                    url: 'https://freefrontend.com/',
                    key: '0-0-0-0-0-3',
                  },
                  {
                    dateAdded: 1669085279478,
                    id: '71',
                    index: 4,
                    parentId: '66',
                    title: '概念 | webpack 中文文档',
                    url: 'https://webpack.docschina.org/concepts/',
                    key: '0-0-0-0-0-4',
                  },
                  {
                    dateAdded: 1668478074928,
                    id: '72',
                    index: 5,
                    parentId: '66',
                    title: 'ECMAScript 6 简介 - ECMAScript 6入门',
                    url: 'https://es6.ruanyifeng.com/#docs/intro',
                    key: '0-0-0-0-0-5',
                  },
                  {
                    dateAdded: 1667679241403,
                    id: '73',
                    index: 6,
                    parentId: '66',
                    title: '简介 | Vue.js',
                    url: 'https://cn.vuejs.org/guide/introduction.html',
                    key: '0-0-0-0-0-6',
                  },
                  {
                    dateAdded: 1667563539766,
                    id: '74',
                    index: 7,
                    parentId: '66',
                    title:
                      '文档简介 · TypeScript中文网 · TypeScript——JavaScript的超集',
                    url: 'https://www.tslang.cn/docs/home.html',
                    key: '0-0-0-0-0-7',
                  },
                  {
                    dateAdded: 1664317489921,
                    id: '75',
                    index: 8,
                    parentId: '66',
                    title: 'Introduction | Electron',
                    url: 'https://www.electronjs.org/docs/latest/',
                    key: '0-0-0-0-0-8',
                  },
                  {
                    dateAdded: 1663483909911,
                    id: '76',
                    index: 9,
                    parentId: '66',
                    title:
                      'CodePen: Online Code Editor and Front End Web Developer Community',
                    url: 'https://codepen.io/',
                    key: '0-0-0-0-0-9',
                  },
                  {
                    dateAdded: 1663483920639,
                    id: '77',
                    index: 10,
                    parentId: '66',
                    title: '组件 | Element',
                    url: 'https://element.eleme.cn/#/zh-CN/component/layout',
                    key: '0-0-0-0-0-10',
                  },
                  {
                    dateAdded: 1666501442796,
                    id: '78',
                    index: 11,
                    parentId: '66',
                    title: 'Apache ECharts',
                    url: 'https://echarts.apache.org/zh/index.html',
                    key: '0-0-0-0-0-11',
                  },
                  {
                    dateAdded: 1672931475137,
                    id: '79',
                    index: 12,
                    parentId: '66',
                    title:
                      'Animate.css | A cross-browser library of CSS animations.',
                    url: 'https://animate.style/',
                    key: '0-0-0-0-0-12',
                  },
                  {
                    dateAdded: 1672931520882,
                    id: '80',
                    index: 13,
                    parentId: '66',
                    title: 'wow.js — Reveal Animations When Scrolling',
                    url: 'https://wowjs.uk/',
                    key: '0-0-0-0-0-13',
                  },
                  {
                    dateAdded: 1673268862832,
                    id: '81',
                    index: 14,
                    parentId: '66',
                    title: 'Font Awesome',
                    url: 'https://fontawesome.com/icons',
                    key: '0-0-0-0-0-14',
                  },
                  {
                    dateAdded: 1669813155061,
                    id: '82',
                    index: 15,
                    parentId: '66',
                    title: 'Iconfont Preview',
                    url: 'http://blog.luckly-mjw.cn/tool-show/iconfont-preview/index.html',
                    key: '0-0-0-0-0-15',
                  },
                  {
                    dateAdded: 1678233851638,
                    id: '195',
                    index: 16,
                    parentId: '66',
                    title: '组件总览 - Ant Design Vue',
                    url: 'https://antdv.com/components/overview-cn',
                    key: '0-0-0-0-0-16',
                  },
                  {
                    dateAdded: 1682006955358,
                    id: '196',
                    index: 17,
                    parentId: '66',
                    title: '为什么你应该使用 Vuetify — Vuetify',
                    url: 'https://v2.vuetifyjs.com/zh-Hans/introduction/why-vuetify/',
                    key: '0-0-0-0-0-17',
                  },
                  {
                    dateAdded: 1683803142697,
                    id: '278',
                    index: 18,
                    parentId: '66',
                    title: 'Installation - Tailwind CSS',
                    url: 'https://tailwindcss.com/docs/installation',
                    key: '0-0-0-0-0-18',
                  },
                  {
                    dateAdded: 1686365914975,
                    id: '281',
                    index: 19,
                    parentId: '66',
                    title: '起步 | VueUse中文文档',
                    url: 'https://www.vueusejs.com/guide/',
                    key: '0-0-0-0-0-19',
                  },
                  {
                    dateAdded: 1697609627774,
                    id: '654',
                    index: 20,
                    parentId: '66',
                    title: 'anime.js • JavaScript animation engine',
                    url: 'https://animejs.com/',
                    key: '0-0-0-0-0-20',
                  },
                ],
                dateAdded: 1674212508064,
                dateGroupModified: 1697629718040,
                id: '66',
                index: 0,
                parentId: '65',
                title: '前端',
                key: '0-0-0-0-0',
              },
              {
                children: [
                  {
                    dateAdded: 1662168615064,
                    id: '84',
                    index: 0,
                    parentId: '83',
                    title: 'LintCode 领扣',
                    url: 'https://www.lintcode.com/',
                    key: '0-0-0-0-1-0',
                  },
                  {
                    dateAdded: 1662168192014,
                    id: '85',
                    index: 1,
                    parentId: '83',
                    title: '力扣（LeetCode）官网 - 全球极客挚爱的技术成长平台',
                    url: 'https://leetcode-cn.com/',
                    key: '0-0-0-0-1-1',
                  },
                  {
                    dateAdded: 1665587508412,
                    id: '86',
                    index: 2,
                    parentId: '83',
                    title: '首页 - 洛谷 | 计算机科学教育新生态',
                    url: 'https://www.luogu.com.cn/',
                    key: '0-0-0-0-1-2',
                  },
                  {
                    dateAdded: 1665587640234,
                    id: '87',
                    index: 3,
                    parentId: '83',
                    title: '题目列表 - 洛谷 | 计算机科学教育新生态',
                    url: 'https://www.luogu.com.cn/problem/list?type=P&page=1',
                    key: '0-0-0-0-1-3',
                  },
                  {
                    dateAdded: 1672546491538,
                    id: '88',
                    index: 4,
                    parentId: '83',
                    title: 'AcWing',
                    url: 'https://www.acwing.com/',
                    key: '0-0-0-0-1-4',
                  },
                  {
                    dateAdded: 1672546591997,
                    id: '89',
                    index: 5,
                    parentId: '83',
                    title: '蓝桥杯大赛',
                    url: 'https://dasai.lanqiao.cn/profile?ut=0',
                    key: '0-0-0-0-1-5',
                  },
                  {
                    dateAdded: 1662168230243,
                    id: '90',
                    index: 6,
                    parentId: '83',
                    title: '牛客网',
                    url: 'https://www.nowcoder.com/',
                    key: '0-0-0-0-1-6',
                  },
                ],
                dateAdded: 1674212508066,
                id: '83',
                index: 1,
                parentId: '65',
                title: '刷题网站',
                key: '0-0-0-0-1',
              },
              {
                children: [
                  {
                    dateAdded: 1662168103690,
                    id: '92',
                    index: 0,
                    parentId: '91',
                    title: '虚幻引擎4文档 | Unreal Engine Documentation',
                    url: 'https://docs.unrealengine.com/zh-CN/index.html',
                    key: '0-0-0-0-2-0',
                  },
                  {
                    dateAdded: 1671066172401,
                    id: '93',
                    index: 1,
                    parentId: '91',
                    title: '虚幻引擎5.1文档 | 虚幻引擎5.1文档',
                    url: 'https://docs.unrealengine.com/5.1/zh-CN/',
                    key: '0-0-0-0-2-1',
                  },
                  {
                    dateAdded: 1662168113378,
                    id: '94',
                    index: 2,
                    parentId: '91',
                    title: 'Unity 用户手册 (2018.4) - Unity 手册',
                    url: 'https://docs.unity.cn/cn/current/Manual/index.html',
                    key: '0-0-0-0-2-2',
                  },
                  {
                    dateAdded: 1662168552704,
                    id: '95',
                    index: 3,
                    parentId: '91',
                    title:
                      'Hellocjc | 虚幻4 | UE4 | 免费教程 | 资源 | 游戏 | 谌嘉诚 – 从自学到就业！',
                    url: 'https://www.hellocjc.com/',
                    key: '0-0-0-0-2-3',
                  },
                ],
                dateAdded: 1674212508066,
                id: '91',
                index: 2,
                parentId: '65',
                title: '游戏开发',
                key: '0-0-0-0-2',
              },
              {
                children: [
                  {
                    dateAdded: 1662168646338,
                    id: '97',
                    index: 0,
                    parentId: '96',
                    title: '墨鱼设计-素材解析',
                    url: 'http://ali.mouae.com/home/',
                    key: '0-0-0-0-3-0',
                  },
                  {
                    dateAdded: 1662168651524,
                    id: '98',
                    index: 1,
                    parentId: '96',
                    title: '模板首页 - ProcessOn',
                    url: 'https://www.processon.com/diagrams/new#template',
                    key: '0-0-0-0-3-1',
                  },
                  {
                    dateAdded: 1662168670535,
                    id: '99',
                    index: 2,
                    parentId: '96',
                    title: '面试鸭 - 助你成为面试达人',
                    url: 'https://www.mianshiya.com/',
                    key: '0-0-0-0-3-2',
                  },
                  {
                    dateAdded: 1665059522697,
                    id: '100',
                    index: 3,
                    parentId: '96',
                    title: 'iconfont-阿里巴巴矢量图标库',
                    url: 'https://www.iconfont.cn/',
                    key: '0-0-0-0-3-3',
                  },
                  {
                    dateAdded: 1670859269225,
                    id: '101',
                    index: 4,
                    parentId: '96',
                    title: 'Sketch - Discover',
                    url: 'https://www.sketch.com/workspace/e0204213-dd90-4ed0-8d65-86bbbe520a1b/discover',
                    key: '0-0-0-0-3-4',
                  },
                  {
                    dateAdded: 1670860233420,
                    id: '102',
                    index: 5,
                    parentId: '96',
                    title: '最近打开-Pixso',
                    url: 'https://pixso.cn/app/recent',
                    key: '0-0-0-0-3-5',
                  },
                  {
                    dateAdded: 1670860349856,
                    id: '103',
                    index: 6,
                    parentId: '96',
                    title: '墨刀-高效产设研协同平台',
                    url: 'https://modao.cc/brand',
                    key: '0-0-0-0-3-6',
                  },
                  {
                    dateAdded: 1670893492968,
                    id: '104',
                    index: 7,
                    parentId: '96',
                    title: 'Recently viewed – Figma',
                    url: 'https://www.figma.com/files/recent?fuid=1184299242105128994',
                    key: '0-0-0-0-3-7',
                  },
                  {
                    dateAdded: 1670902834713,
                    id: '105',
                    index: 8,
                    parentId: '96',
                    title:
                      'Figma 中文社区_插件组件库,软件汉化教程 - Figma.Cool',
                    url: 'https://www.figma.cool/',
                    key: '0-0-0-0-3-8',
                  },
                  {
                    dateAdded: 1673089243268,
                    id: '106',
                    index: 9,
                    parentId: '96',
                    title: '100font.com - 免费字体下载 - 免费商用字体下载网站',
                    url: 'https://www.100font.com/',
                    key: '0-0-0-0-3-9',
                  },
                ],
                dateAdded: 1674212508067,
                id: '96',
                index: 3,
                parentId: '65',
                title: '设计',
                key: '0-0-0-0-3',
              },
              {
                children: [
                  {
                    dateAdded: 1666516257005,
                    id: '108',
                    index: 0,
                    parentId: '107',
                    title: 'Staticfile CDN',
                    url: 'http://www.staticfile.org/',
                    key: '0-0-0-0-4-0',
                  },
                  {
                    dateAdded: 1672374170616,
                    id: '109',
                    index: 1,
                    parentId: '107',
                    title: 'API - Dashboard',
                    url: 'https://tinify.com/dashboard/api#token/1GGzt336975rgZ93DqTZXyxNvqczx7m6/zE5_Qng_',
                    key: '0-0-0-0-4-1',
                  },
                  {
                    dateAdded: 1672222667233,
                    id: '110',
                    index: 2,
                    parentId: '107',
                    title: 'HelloGitHub',
                    url: 'https://hellogithub.com/',
                    key: '0-0-0-0-4-2',
                  },
                  {
                    dateAdded: 1670316901220,
                    id: '111',
                    index: 3,
                    parentId: '107',
                    title: 'ChatGPT',
                    url: 'https://chat.openai.com/chat',
                    key: '0-0-0-0-4-3',
                  },
                  {
                    dateAdded: 1670287581418,
                    id: '112',
                    index: 4,
                    parentId: '107',
                    title: '教育 - Microsoft Azure',
                    url: 'https://portal.azure.com/?Microsoft_Azure_Education_correlationId=e9e31b73-8382-4405-92ee-e15eb666e628&Microsoft_Azure_Education_newA4E=true&Microsoft_Azure_Education_asoSubGuid=3e074c86-4a31-4fa3-8b8b-657a0cba8949#view/Microsoft_Azure_Education/EducationMenuBlade/~/overview',
                    key: '0-0-0-0-4-4',
                  },
                  {
                    dateAdded: 1673183557445,
                    id: '113',
                    index: 5,
                    parentId: '107',
                    title: 'DALL·E',
                    url: 'https://labs.openai.com/',
                    key: '0-0-0-0-4-5',
                  },
                  {
                    dateAdded: 1675689954776,
                    id: '197',
                    index: 6,
                    parentId: '107',
                    title: 'Docker',
                    url: 'https://hub.docker.com/',
                    key: '0-0-0-0-4-6',
                  },
                  {
                    dateAdded: 1689168574280,
                    id: '376',
                    index: 7,
                    parentId: '107',
                    title: 'Browse Fonts - Google Fonts',
                    url: 'https://fonts.google.com/',
                    key: '0-0-0-0-4-7',
                  },
                ],
                dateAdded: 1674212508067,
                dateGroupModified: 1697543249869,
                id: '107',
                index: 4,
                parentId: '65',
                title: '编程资源',
                key: '0-0-0-0-4',
              },
              {
                children: [
                  {
                    dateAdded: 1662168588110,
                    id: '115',
                    index: 0,
                    parentId: '114',
                    title: '技术文档 | 微软文档',
                    url: 'https://docs.microsoft.com/en-us/documentation/',
                    key: '0-0-0-0-5-0',
                  },
                  {
                    dateAdded: 1669013941310,
                    id: '116',
                    index: 1,
                    parentId: '114',
                    title: 'Quick Reference & 奇链 - 一个神奇的网站',
                    url: 'https://www.dbyun.net/reference/index.html',
                    key: '0-0-0-0-5-1',
                  },
                  {
                    dateAdded: 1669282598128,
                    id: '117',
                    index: 2,
                    parentId: '114',
                    title: 'DevDocs API Documentation',
                    url: 'https://devdocs.io/',
                    key: '0-0-0-0-5-2',
                  },
                  {
                    dateAdded: 1668041621067,
                    id: '118',
                    index: 3,
                    parentId: '114',
                    title: 'w3school 在线教程',
                    url: 'https://www.w3school.com.cn/index.html',
                    key: '0-0-0-0-5-3',
                  },
                  {
                    dateAdded: 1668156531232,
                    id: '119',
                    index: 4,
                    parentId: '114',
                    title:
                      '(2条消息) C++11并发与多线程_胡胡浩特的博客-CSDN博客',
                    url: 'https://blog.csdn.net/qq_38231713/category_10001159.html',
                    key: '0-0-0-0-5-4',
                  },
                  {
                    dateAdded: 1662167849681,
                    id: '120',
                    index: 5,
                    parentId: '114',
                    title: '菜鸟教程 - 学的不仅是技术，更是梦想！',
                    url: 'https://www.runoob.com/',
                    key: '0-0-0-0-5-5',
                  },
                  {
                    dateAdded: 1666259191822,
                    id: '121',
                    index: 6,
                    parentId: '114',
                    title: '无涯教程 - 程序员零基础入门自学编程,IT在线学习平台',
                    url: 'https://www.learnfk.com/',
                    key: '0-0-0-0-5-6',
                  },
                  {
                    dateAdded: 1662168568553,
                    id: '122',
                    index: 7,
                    parentId: '114',
                    title: '课程-KuangStudy',
                    url: 'https://www.kuangstudy.com/course',
                    key: '0-0-0-0-5-7',
                  },
                  {
                    dateAdded: 1663509221531,
                    id: '123',
                    index: 8,
                    parentId: '114',
                    title: '鱼皮 - 编程学习路线',
                    url: 'https://luxian.yupi.icu/',
                    key: '0-0-0-0-5-8',
                  },
                ],
                dateAdded: 1674212508068,
                id: '114',
                index: 5,
                parentId: '65',
                title: '综合文档',
                key: '0-0-0-0-5',
              },
              {
                children: [
                  {
                    dateAdded: 1669645435310,
                    id: '125',
                    index: 0,
                    parentId: '124',
                    title: '稀土掘金',
                    url: 'https://juejin.cn/',
                    key: '0-0-0-0-6-0',
                  },
                  {
                    dateAdded: 1662168170777,
                    id: '126',
                    index: 1,
                    parentId: '124',
                    title:
                      'Stack Overflow - Where Developers Learn, Share, & Build Careers',
                    url: 'https://stackoverflow.com/',
                    key: '0-0-0-0-6-1',
                  },
                ],
                dateAdded: 1674212508069,
                id: '124',
                index: 6,
                parentId: '65',
                title: '交流平台',
                key: '0-0-0-0-6',
              },
              {
                children: [
                  {
                    dateAdded: 1662168205870,
                    id: '128',
                    index: 0,
                    parentId: '127',
                    title: 'python install',
                    url: 'https://pypi.tuna.tsinghua.edu.cn/simple/',
                    key: '0-0-0-0-7-0',
                  },
                  {
                    dateAdded: 1662168219009,
                    id: '129',
                    index: 1,
                    parentId: '127',
                    title:
                      'Python Extension Packages for Windows - Christoph Gohlke',
                    url: 'https://www.lfd.uci.edu/~gohlke/pythonlibs/',
                    key: '0-0-0-0-7-1',
                  },
                  {
                    dateAdded: 1662168267503,
                    id: '130',
                    index: 2,
                    parentId: '127',
                    title: 'The latest in machine learning | Papers With Code',
                    url: 'https://paperswithcode.com/',
                    key: '0-0-0-0-7-2',
                  },
                ],
                dateAdded: 1674212508069,
                id: '127',
                index: 7,
                parentId: '65',
                title: 'AI',
                key: '0-0-0-0-7',
              },
              {
                children: [
                  {
                    dateAdded: 1667388380118,
                    id: '132',
                    index: 0,
                    parentId: '131',
                    title: 'GitHub 文件加速',
                    url: 'https://gh.api.99988866.xyz/',
                    key: '0-0-0-0-8-0',
                  },
                  {
                    dateAdded: 1672133190166,
                    id: '133',
                    index: 1,
                    parentId: '131',
                    title:
                      '代码在线高亮工具 | 将高亮美化的代码一键粘贴到 Word 或 OneNote 中',
                    url: 'https://highlightcode.com/',
                    key: '0-0-0-0-8-1',
                  },
                  {
                    dateAdded: 1673073767914,
                    id: '134',
                    index: 2,
                    parentId: '131',
                    title:
                      'Shields.io: Quality metadata badges for open source projects',
                    url: 'https://shields.io/',
                    key: '0-0-0-0-8-2',
                  },
                  {
                    dateAdded: 1673091597229,
                    id: '135',
                    index: 3,
                    parentId: '131',
                    title:
                      '🎁 Emoji cheat sheet for GitHub, Basecamp, Slack & more',
                    url: 'https://www.webfx.com/tools/emoji-cheat-sheet/',
                    key: '0-0-0-0-8-3',
                  },
                  {
                    dateAdded: 1673092866327,
                    id: '136',
                    index: 4,
                    parentId: '131',
                    title:
                      'github-readme-stats/readme_cn.md at master · anuraghazra/github-readme-stats',
                    url: 'https://github.com/anuraghazra/github-readme-stats/blob/master/docs/readme_cn.md#%E4%B8%BB%E9%A2%98',
                    key: '0-0-0-0-8-4',
                  },
                  {
                    dateAdded: 1673092985385,
                    id: '137',
                    index: 5,
                    parentId: '131',
                    title:
                      'GitHub Profile Readme Generator | GitHub Profile Readme Generator',
                    url: 'https://rahuldkjain.github.io/gh-profile-readme-generator/',
                    key: '0-0-0-0-8-5',
                  },
                  {
                    dateAdded: 1673093395910,
                    id: '138',
                    index: 6,
                    parentId: '131',
                    title:
                      'jamesgeorge007/github-activity-readme: Updates README with the recent GitHub activity of a user',
                    url: 'https://github.com/jamesgeorge007/github-activity-readme',
                    key: '0-0-0-0-8-6',
                  },
                  {
                    dateAdded: 1673093404704,
                    id: '139',
                    index: 7,
                    parentId: '131',
                    title:
                      'abhisheknaiidu/awesome-github-profile-readme: 😎 A curated list of awesome GitHub Profile READMEs 📝',
                    url: 'https://github.com/abhisheknaiidu/awesome-github-profile-readme#tools',
                    key: '0-0-0-0-8-7',
                  },
                  {
                    dateAdded: 1675931425243,
                    id: '198',
                    index: 8,
                    parentId: '131',
                    title: 'Excalidraw',
                    url: 'https://excalidraw.com/',
                    key: '0-0-0-0-8-8',
                  },
                  {
                    dateAdded: 1679464349756,
                    id: '199',
                    index: 9,
                    parentId: '131',
                    title: 'Getting Started',
                    url: 'https://www.notion.so/Getting-Started-ed04b2b55827437ca05a6804ac7fb7b2',
                    key: '0-0-0-0-8-9',
                  },
                  {
                    dateAdded: 1683976048371,
                    id: '456',
                    index: 10,
                    parentId: '131',
                    title:
                      'iP地址查询--手机号码查询归属地 | 邮政编码查询 | iP地址归属地查询 | 身份证号码验证在线查询网',
                    url: 'https://www.ip138.com/',
                    key: '0-0-0-0-8-10',
                  },
                  {
                    dateAdded: 1684421369151,
                    id: '459',
                    index: 11,
                    parentId: '131',
                    title: '用户中心 — 最萌の云 - CuteCloud',
                    url: 'https://www.cutecloud.net/user',
                    key: '0-0-0-0-8-11',
                  },
                  {
                    dateAdded: 1685619417147,
                    id: '462',
                    index: 12,
                    parentId: '131',
                    title: 'md5在线解密破解,md5解密加密',
                    url: 'https://www.cmd5.com/',
                    key: '0-0-0-0-8-12',
                  },
                  {
                    dateAdded: 1685767242013,
                    id: '465',
                    index: 13,
                    parentId: '131',
                    title: 'Database diagrams',
                    url: 'https://drawsql.app/diagrams',
                    key: '0-0-0-0-8-13',
                  },
                  {
                    dateAdded: 1686270665214,
                    id: '468',
                    index: 14,
                    parentId: '131',
                    title: '韩小韩API接口站 - 免费API数据接口调用服务平台',
                    url: 'https://api.vvhan.com/',
                    key: '0-0-0-0-8-14',
                  },
                  {
                    dateAdded: 1686579059821,
                    id: '471',
                    index: 15,
                    parentId: '131',
                    title: 'Your Projects - Overleaf, Online LaTeX Editor',
                    url: 'https://www.overleaf.com/project',
                    key: '0-0-0-0-8-15',
                  },
                  {
                    dateAdded: 1690775041281,
                    id: '474',
                    index: 16,
                    parentId: '131',
                    title: 'flow.aliyun.com',
                    url: 'https://flow.aliyun.com/',
                    key: '0-0-0-0-8-16',
                  },
                  {
                    dateAdded: 1697601767009,
                    id: '650',
                    index: 17,
                    parentId: '131',
                    title:
                      'StarryFrp - 星空内网穿透 | 免费的内网穿透_免费端口映射_我的世界开服映射',
                    url: 'https://frp.starryfrp.com/',
                    key: '0-0-0-0-8-17',
                  },
                  {
                    dateAdded: 1697601784832,
                    id: '651',
                    index: 18,
                    parentId: '131',
                    title: '首页 | LoCyanFrp',
                    url: 'https://preview.locyanfrp.cn/',
                    key: '0-0-0-0-8-18',
                  },
                  {
                    dateAdded: 1697629718040,
                    id: '655',
                    index: 19,
                    parentId: '131',
                    title: 'Facetype.js',
                    url: 'https://gero3.github.io/facetype.js/',
                    key: '0-0-0-0-8-19',
                  },
                  {
                    dateAdded: 1699361283451,
                    id: '661',
                    index: 20,
                    parentId: '131',
                    title: 'CODELF',
                    url: 'https://unbug.github.io/codelf/',
                    key: '0-0-0-0-8-20',
                  },
                  {
                    dateAdded: 1700357722970,
                    id: '664',
                    index: 21,
                    parentId: '131',
                    title: 'Abbreviations.com',
                    url: 'https://www.abbreviations.com/',
                    key: '0-0-0-0-8-21',
                  },
                ],
                dateAdded: 1674212508069,
                dateGroupModified: 1700641541148,
                id: '131',
                index: 8,
                parentId: '65',
                title: '工具',
                key: '0-0-0-0-8',
              },
              {
                children: [
                  {
                    dateAdded: 1672931854844,
                    id: '141',
                    index: 0,
                    parentId: '140',
                    title: 'Manim Kindergarten',
                    url: 'https://manim.org.cn/docs',
                    key: '0-0-0-0-9-0',
                  },
                  {
                    dateAdded: 1675692332928,
                    id: '200',
                    index: 1,
                    parentId: '140',
                    title: 'Quickstart - Manim Community v0.17.2',
                    url: 'https://docs.manim.community/en/stable/tutorials/quickstart.html',
                    key: '0-0-0-0-9-1',
                  },
                ],
                dateAdded: 1674212508070,
                id: '140',
                index: 9,
                parentId: '65',
                title: '视频制作',
                key: '0-0-0-0-9',
              },
              {
                children: [
                  {
                    dateAdded: 1673665575303,
                    id: '143',
                    index: 0,
                    parentId: '142',
                    title:
                      'Beautiful Soup 4.4.0 文档 — Beautiful Soup 4.2.0 中文 文档',
                    url: 'https://beautifulsoup.readthedocs.io/zh_CN/v4.4.0/',
                    key: '0-0-0-0-10-0',
                  },
                ],
                dateAdded: 1674212508070,
                id: '142',
                index: 10,
                parentId: '65',
                title: '爬虫',
                key: '0-0-0-0-10',
              },
              {
                children: [
                  {
                    dateAdded: 1674095455554,
                    id: '145',
                    index: 0,
                    parentId: '144',
                    title: 'mybatis – MyBatis 3 | 简介',
                    url: 'https://mybatis.org/mybatis-3/zh/index.html',
                    key: '0-0-0-0-11-0',
                  },
                  {
                    dateAdded: 1689909264412,
                    id: '495',
                    index: 1,
                    parentId: '144',
                    title: 'How2J 的 Java教程',
                    url: 'https://how2j.cn/',
                    key: '0-0-0-0-11-1',
                  },
                ],
                dateAdded: 1674212508070,
                id: '144',
                index: 11,
                parentId: '65',
                title: '后端',
                key: '0-0-0-0-11',
              },
              {
                children: [
                  {
                    dateAdded: 1678875037405,
                    id: '202',
                    index: 0,
                    parentId: '201',
                    title: 'wanting-railway | Railway',
                    url: 'https://railway.app/project/9a73551e-7646-46d9-b737-cf4a256465cd',
                    key: '0-0-0-0-12-0',
                  },
                  {
                    dateAdded: 1699324525675,
                    id: '659',
                    index: 1,
                    parentId: '201',
                    title: 'Dashboard – Vercel',
                    url: 'https://vercel.com/',
                    key: '0-0-0-0-12-1',
                  },
                ],
                dateAdded: 1683421321166,
                dateGroupModified: 1699361283451,
                id: '201',
                index: 12,
                parentId: '65',
                title: '部署',
                key: '0-0-0-0-12',
              },
              {
                children: [
                  {
                    dateAdded: 1685495649010,
                    id: '505',
                    index: 0,
                    parentId: '502',
                    title: '数据结构和算法动态可视化 (Chinese) - VisuAlgo',
                    url: 'https://visualgo.net/zh',
                    key: '0-0-0-0-13-0',
                  },
                ],
                dateAdded: 1690800985382,
                id: '502',
                index: 13,
                parentId: '65',
                title: '算法',
                key: '0-0-0-0-13',
              },
              {
                children: [
                  {
                    dateAdded: 1691321483213,
                    id: '620',
                    index: 0,
                    parentId: '621',
                    title: 'YApi Pro-高效、易用、功能强大的可视化接口管理平台',
                    url: 'https://yapi.pro/',
                    key: '0-0-0-0-14-0',
                  },
                  {
                    dateAdded: 1700641541148,
                    id: '667',
                    index: 1,
                    parentId: '621',
                    title: 'fastmock.site/#/',
                    url: 'https://www.fastmock.site/#/',
                    key: '0-0-0-0-14-1',
                  },
                ],
                dateAdded: 1691321509518,
                dateGroupModified: 1700641545750,
                id: '621',
                index: 14,
                parentId: '65',
                title: '接口工具',
                key: '0-0-0-0-14',
              },
              {
                children: [
                  {
                    dateAdded: 1695603510473,
                    id: '635',
                    index: 0,
                    parentId: '637',
                    title: 'ManyPixels – Unlimited Graphic Design | Try Now',
                    url: 'https://www.manypixels.co/',
                    key: '0-0-0-0-15-0',
                  },
                  {
                    dateAdded: 1695603698707,
                    id: '638',
                    index: 1,
                    parentId: '637',
                    title:
                      'Free illustrations | Free to use PNG vector SVG illustrations',
                    url: 'https://freeillustrations.xyz/',
                    key: '0-0-0-0-15-1',
                  },
                  {
                    dateAdded: 1695603737973,
                    id: '639',
                    index: 2,
                    parentId: '637',
                    title:
                      'Premium WordPress Themes, Templates & Plugins @ ThemeIsle',
                    url: 'https://themeisle.com/',
                    key: '0-0-0-0-15-2',
                  },
                  {
                    dateAdded: 1695603753362,
                    id: '640',
                    index: 3,
                    parentId: '637',
                    title:
                      'Popsy - No-code website builder that works like Notion',
                    url: 'https://popsy.co/',
                    key: '0-0-0-0-15-3',
                  },
                  {
                    dateAdded: 1695603778662,
                    id: '641',
                    index: 4,
                    parentId: '637',
                    title: 'Illustrations | unDraw',
                    url: 'https://undraw.co/illustrations',
                    key: '0-0-0-0-15-4',
                  },
                  {
                    dateAdded: 1695603794268,
                    id: '642',
                    index: 5,
                    parentId: '637',
                    title: 'Loose Drawing|無料で商用利用可なフリーイラスト',
                    url: 'https://loosedrawing.com/',
                    key: '0-0-0-0-15-5',
                  },
                ],
                dateAdded: 1695603574578,
                dateGroupModified: 1696664392024,
                id: '637',
                index: 15,
                parentId: '65',
                title: '编程设计资源',
                key: '0-0-0-0-15',
              },
            ],
            dateAdded: 1674212508064,
            dateGroupModified: 1695603574579,
            id: '65',
            index: 0,
            parentId: '1',
            title: '编程',
            key: '0-0-0-0',
          },
          {
            children: [
              {
                dateAdded: 1662167938339,
                id: '147',
                index: 0,
                parentId: '146',
                title: 'CC0 Textures - Public Domain PBR Materials',
                url: 'https://cc0textures.com/',
                key: '0-0-0-1-0',
              },
              {
                dateAdded: 1662167953449,
                id: '148',
                index: 1,
                parentId: '146',
                title: 'HDRI Haven',
                url: 'https://hdrihaven.com/',
                key: '0-0-0-1-1',
              },
              {
                dateAdded: 1662167977454,
                id: '149',
                index: 2,
                parentId: '146',
                title: '3D Model Haven',
                url: 'https://3dmodelhaven.com/',
                key: '0-0-0-1-2',
              },
              {
                dateAdded: 1662167997395,
                id: '150',
                index: 3,
                parentId: '146',
                title: 'Texture Haven',
                url: 'https://texturehaven.com/',
                key: '0-0-0-1-3',
              },
              {
                dateAdded: 1662168032737,
                id: '151',
                index: 4,
                parentId: '146',
                title: 'Search - marble',
                url: 'https://www.textures.com/search?q=marble',
                key: '0-0-0-1-4',
              },
              {
                dateAdded: 1662168048331,
                id: '152',
                index: 5,
                parentId: '146',
                title: 'wall cladding stone textures seamless',
                url: 'https://www.sketchuptextureclub.com/textures/architecture/stones-walls/claddings-stone',
                key: '0-0-0-1-5',
              },
              {
                dateAdded: 1697543289818,
                id: '649',
                index: 6,
                parentId: '146',
                title: 'Home · Kenney',
                url: 'https://www.kenney.nl/',
                key: '0-0-0-1-6',
              },
            ],
            dateAdded: 1674212508070,
            dateGroupModified: 1697601767009,
            id: '146',
            index: 1,
            parentId: '1',
            title: '材质',
            key: '0-0-0-1',
          },
          {
            children: [
              {
                dateAdded: 1662168311328,
                id: '157',
                index: 0,
                parentId: '153',
                title:
                  '中国高清网 | 高清电影网|720P|1080P|蓝光原盘|磁力链迅雷下载高清的电影天堂',
                url: 'http://gaoqing.la/',
                key: '0-0-0-2-0',
              },
              {
                dateAdded: 1662168459860,
                id: '158',
                index: 1,
                parentId: '153',
                title:
                  '酷Q网音乐格式转换 - 酷狗酷我QQ音乐网易云音乐虾米音乐ncm,qmc,mflac,mgg,kgm.kwm加密音乐格式转换成MP3',
                url: 'https://mp3.aoleiao.com/',
                key: '0-0-0-2-1',
              },
              {
                dateAdded: 1662168474551,
                id: '159',
                index: 2,
                parentId: '153',
                title:
                  '中国高清电影网|高清网|720P|1080P|蓝光原盘|磁力链迅雷下载高清的电影天堂',
                url: 'http://www.gaoqingw.com/',
                key: '0-0-0-2-2',
              },
              {
                dateAdded: 1662168678243,
                id: '160',
                index: 3,
                parentId: '153',
                title: '贝贝BiliBili - B站视频下载',
                url: 'https://xbeibeix.com/api/bilibili/',
                key: '0-0-0-2-3',
              },
              {
                dateAdded: 1667028722588,
                id: '161',
                index: 4,
                parentId: '153',
                title:
                  '花猫壁纸 - 致力打造属于年轻人的世界 - 在这里不只有壁纸等你发现',
                url: 'http://huamao.vip/',
                key: '0-0-0-2-4',
              },
              {
                dateAdded: 1668086353195,
                id: '162',
                index: 5,
                parentId: '153',
                title: 'Some keys for testing - jetbra.in',
                url: 'https://bafybeiatyghkzrrtodzt3stm652rkrjxndg4hq2ublfdmifk7plg5k5brq.ipfs.storry.tv/',
                key: '0-0-0-2-5',
              },
              {
                dateAdded: 1670249886350,
                id: '163',
                index: 6,
                parentId: '153',
                title: '在线接受短信的虚拟号码 - SMS-Activate',
                url: 'https://sms-activate.org/cn',
                key: '0-0-0-2-6',
              },
              {
                dateAdded: 1670250777557,
                id: '164',
                index: 7,
                parentId: '153',
                title: 'clashx',
                url: 'https://github.com/Fndroid/clash_for_windows_pkg/releases',
                key: '0-0-0-2-7',
              },
              {
                dateAdded: 1671338247177,
                id: '165',
                index: 8,
                parentId: '153',
                title: 'Awesome Wallpapers - wallhaven.cc',
                url: 'https://wallhaven.cc/',
                key: '0-0-0-2-8',
              },
              {
                dateAdded: 1673593705348,
                id: '166',
                index: 9,
                parentId: '153',
                title: 'zhelper Search Page 搜索界面 🔍',
                url: 'https://search.zhelper.net/?[{%22name%22:%22Ylibrary%22,%22url%22:%22https://api.ylibrary.org%22,%22type%22:%22full%22,%22sensitive%22:false,%22detail%22:true}]',
                key: '0-0-0-2-9',
              },
              {
                dateAdded: 1673593721450,
                id: '167',
                index: 10,
                parentId: '153',
                title: 'zhelper search 配置小工具',
                url: 'https://tool.yibook.org/',
                key: '0-0-0-2-10',
              },
              {
                dateAdded: 1674048217556,
                id: '168',
                index: 11,
                parentId: '153',
                title: '西西资源官网-影视动漫资源-音乐专辑-网红写真-软件插件',
                url: 'https://www.xixi521.com/',
                key: '0-0-0-2-11',
              },
              {
                dateAdded: 1674048494324,
                id: '169',
                index: 12,
                parentId: '153',
                title: 'BTNull - 无名小站',
                url: 'https://www.btnull.in/',
                key: '0-0-0-2-12',
              },
              {
                dateAdded: 1675587399408,
                id: '203',
                index: 13,
                parentId: '153',
                title: 'Uberduck - Make cool stuff with AI and text to speech',
                url: 'https://app.uberduck.ai/',
                key: '0-0-0-2-13',
              },
              {
                dateAdded: 1675616651488,
                id: '204',
                index: 14,
                parentId: '153',
                title: '爱分享导航_收录你喜欢的网站',
                url: 'https://ifxdh.com/',
                key: '0-0-0-2-14',
              },
              {
                dateAdded: 1676780371263,
                id: '205',
                index: 15,
                parentId: '153',
                title:
                  'Civitai | Stable Diffusion models, embeddings, hypernetworks and more',
                url: 'https://civitai.com/',
                key: '0-0-0-2-15',
              },
              {
                dateAdded: 1679741200558,
                id: '206',
                index: 16,
                parentId: '153',
                title: '渐构 Modevol',
                url: 'https://www.modevol.com/',
                key: '0-0-0-2-16',
              },
              {
                dateAdded: 1683946727231,
                id: '563',
                index: 17,
                parentId: '153',
                title: 'Thingiverse - Digital Designs for Physical Objects',
                url: 'https://www.thingiverse.com/',
                key: '0-0-0-2-17',
              },
              {
                dateAdded: 1687176666694,
                id: '565',
                index: 18,
                parentId: '153',
                title: 'ct | AList',
                url: 'http://150.158.214.32:5244/ct',
                key: '0-0-0-2-18',
              },
              {
                dateAdded: 1692583527357,
                id: '623',
                index: 19,
                parentId: '153',
                title: 'Sketchfab - The best 3D viewer on the web',
                url: 'https://sketchfab.com/',
                key: '0-0-0-2-19',
              },
              {
                dateAdded: 1693828454100,
                id: '625',
                index: 20,
                parentId: '153',
                title: '人人影视网 - 人人影视字幕组成立的美剧观影平台',
                url: 'https://www.rqsxbyc.com/',
                key: '0-0-0-2-20',
              },
              {
                dateAdded: 1694445565380,
                id: '629',
                index: 21,
                parentId: '153',
                title: '电影狗 - 专业电影搜索引擎',
                url: 'https://www.dianyinggou.com/',
                key: '0-0-0-2-21',
              },
              {
                dateAdded: 1696664392024,
                id: '645',
                index: 22,
                parentId: '153',
                title: '导航文库 - ApacheCN',
                url: 'https://docs.apachecn.org/',
                key: '0-0-0-2-22',
              },
            ],
            dateAdded: 1674212508071,
            dateGroupModified: 1700357722970,
            id: '153',
            index: 2,
            parentId: '1',
            title: '资源',
            key: '0-0-0-2',
          },
          {
            children: [
              {
                dateAdded: 1662168542532,
                id: '171',
                index: 0,
                parentId: '170',
                title:
                  'Welcome to ESP8266 Arduino Core’s documentation! — ESP8266 Arduino Core 2.7.1-107-gbc816c65 documentation',
                url: 'https://arduino-esp8266.readthedocs.io/en/latest/index.html',
                key: '0-0-0-3-0',
              },
            ],
            dateAdded: 1674212508072,
            id: '170',
            index: 3,
            parentId: '1',
            title: '单片机',
            key: '0-0-0-3',
          },
          {
            children: [
              {
                dateAdded: 1664379969578,
                id: '173',
                index: 0,
                parentId: '172',
                title: '江西财经大学--教学管理服务平台',
                url: 'http://xk.jxufe.edu.cn/',
                key: '0-0-0-4-0',
              },
              {
                dateAdded: 1666151457965,
                id: '174',
                index: 1,
                parentId: '172',
                title: '江西财经大学-网络教学中心',
                url: 'http://i.mooc.chaoxing.com/space/index?t=1666151300144',
                key: '0-0-0-4-1',
              },
              {
                dateAdded: 1669025958293,
                id: '175',
                index: 2,
                parentId: '172',
                title: '中国大学MOOC(慕课)_优质在线课程学习平台',
                url: 'https://www.icourse163.org/home.htm?userId=1531265496#/home/course',
                key: '0-0-0-4-2',
              },
              {
                dateAdded: 1670285417185,
                id: '176',
                index: 3,
                parentId: '172',
                title: '腾讯企业邮箱',
                url: 'https://exmail.qq.com/cgi-bin/frame_html?sid=EF5nZhyUmm3jySRH,7&sign_type=&r=36e76926515844f1aac01ec00fac2a86',
                key: '0-0-0-4-3',
              },
              {
                dateAdded: 1670937016706,
                id: '177',
                index: 4,
                parentId: '172',
                title: '江西财经大学',
                url: 'http://www.jxufe.edu.cn/',
                key: '0-0-0-4-4',
              },
              {
                dateAdded: 1669682102573,
                id: '178',
                index: 5,
                parentId: '172',
                title: 'PTA | 程序设计类实验辅助教学平台',
                url: 'https://pintia.cn/problem-sets/dashboard',
                key: '0-0-0-4-5',
              },
              {
                dateAdded: 1672886319388,
                id: '179',
                index: 6,
                parentId: '172',
                title: '江西财经大学邮件登录系统',
                url: 'http://mail.jxufe.edu.cn/',
                key: '0-0-0-4-6',
              },
              {
                dateAdded: 1674181834528,
                id: '180',
                index: 7,
                parentId: '172',
                title: 'U校园',
                url: 'https://u.unipus.cn/user/student?school_id=9439',
                key: '0-0-0-4-7',
              },
              {
                dateAdded: 1674526130020,
                id: '213',
                index: 8,
                parentId: '172',
                title: '《从C语言转C++简明教程 v5.0+》 – 柳婼 の blog',
                url: 'https://www.liuchuo.net/333-3',
                key: '0-0-0-4-8',
              },
              {
                dateAdded: 1678796649845,
                id: '214',
                index: 9,
                parentId: '172',
                title: '江西财经大学综合服务门户平台',
                url: 'http://ehall.jxufe.edu.cn/new/index.html',
                key: '0-0-0-4-9',
              },
              {
                dateAdded: 1688353902376,
                id: '599',
                index: 10,
                parentId: '172',
                title: '江西财经大学网上办事大厅',
                url: 'https://onestop.jxufe.edu.cn/index.jsp',
                key: '0-0-0-4-10',
              },
              {
                dateAdded: 1693887311514,
                id: '627',
                index: 11,
                parentId: '172',
                title: '江西财经大学学工平台',
                url: 'http://ssp.jxufe.edu.cn/admin/common/main.html',
                key: '0-0-0-4-11',
              },
              {
                dateAdded: 1695302544338,
                id: '632',
                index: 12,
                parentId: '172',
                title: '江西财经大学-财务处',
                url: 'http://cwc.jxufe.edu.cn/',
                key: '0-0-0-4-12',
              },
            ],
            dateAdded: 1674212508072,
            dateGroupModified: 1695603510473,
            id: '172',
            index: 4,
            parentId: '1',
            title: '学校',
            key: '0-0-0-4',
          },
          {
            children: [
              {
                dateAdded: 1662167497348,
                id: '182',
                index: 0,
                parentId: '181',
                title: 'Craiyon, formerly DALL-E mini',
                url: 'https://www.craiyon.com/',
                key: '0-0-0-5-0',
              },
              {
                dateAdded: 1662167502645,
                id: '183',
                index: 1,
                parentId: '181',
                title:
                  '🤖 🖼 AI Art Generator, AI Art Maker - NightCafe Creator',
                url: 'https://creator.nightcafe.studio/',
                key: '0-0-0-5-1',
              },
            ],
            dateAdded: 1674212508073,
            id: '181',
            index: 5,
            parentId: '1',
            title: 'AI作画',
            key: '0-0-0-5',
          },
          {
            children: [
              {
                dateAdded: 1662168542532,
                id: '208',
                index: 0,
                parentId: '207',
                title:
                  'Welcome to ESP8266 Arduino Core’s documentation! — ESP8266 Arduino Core 2.7.1-107-gbc816c65 documentation',
                url: 'https://arduino-esp8266.readthedocs.io/en/latest/index.html',
                key: '0-0-0-6-0',
              },
              {
                dateAdded: 1676682681466,
                id: '209',
                index: 1,
                parentId: '207',
                title:
                  '太极创客 – Arduino, ESP8266物联网的应用、开发和学习资料',
                url: 'http://www.taichi-maker.com/',
                key: '0-0-0-6-1',
              },
              {
                dateAdded: 1676725157345,
                id: '210',
                index: 2,
                parentId: '207',
                title: 'LVGL 简介|极客笔记',
                url: 'https://deepinout.com/lvgl-tutorials/lvgl-getting-started/lvgl-intro.html',
                key: '0-0-0-6-2',
              },
              {
                dateAdded: 1676778374326,
                id: '211',
                index: 3,
                parentId: '207',
                title:
                  '欢迎阅读百问网LVGL中文开发手册！ — 百问网LVGL中文教程文档 文档',
                url: 'http://lvgl.100ask.net/8.2/index.html',
                key: '0-0-0-6-3',
              },
              {
                dateAdded: 1677117740265,
                id: '212',
                index: 4,
                parentId: '207',
                title: 'Wokwi - Online Arduino and ESP32 Simulator',
                url: 'https://wokwi.com/',
                key: '0-0-0-6-4',
              },
            ],
            dateAdded: 1683421321167,
            id: '207',
            index: 6,
            parentId: '1',
            title: '嵌入式',
            key: '0-0-0-6',
          },
          {
            children: [
              {
                dateAdded: 1676282811693,
                id: '216',
                index: 0,
                parentId: '215',
                title: '追风逐影，穿越前行 - ourfpv',
                url: 'https://ourfpv.com/',
                key: '0-0-0-7-0',
              },
            ],
            dateAdded: 1683421321168,
            id: '215',
            index: 7,
            parentId: '1',
            title: '穿越机',
            key: '0-0-0-7',
          },
          {
            children: [
              {
                dateAdded: 1689472158939,
                id: '610',
                index: 0,
                parentId: '608',
                title: '搜索画面 - 33搜帧 - 视频帧画面搜索引擎',
                url: 'https://fse.agilestudio.cn/search?keyword=%E7%81%AB%E8%BD%A6%E5%91%BC%E5%95%B8%E8%80%8C%E8%BF%87',
                key: '0-0-0-8-0',
              },
              {
                dateAdded: 1689472366443,
                id: '612',
                index: 1,
                parentId: '608',
                title: 'HeyFriday - Ultimate AI Writer',
                url: 'https://www.heyfriday.ai/article/dashboard',
                key: '0-0-0-8-1',
              },
              {
                dateAdded: 1689472379156,
                id: '614',
                index: 2,
                parentId: '608',
                title:
                  'AI 导航网 | AI教程 | AI集合 | OpenAI | 专注人工智能的导航站',
                url: 'https://www.aidh.ai/',
                key: '0-0-0-8-2',
              },
            ],
            dateAdded: 1690800985383,
            id: '608',
            index: 8,
            parentId: '1',
            title: '视频',
            key: '0-0-0-8',
          },
        ],
        dateAdded: 1661418109722,
        dateGroupModified: 1695603548297,
        id: '1',
        index: 0,
        parentId: '0',
        title: '收藏夹栏',
        key: '0-0-0',
      },
      {
        children: [
          {
            dateAdded: 1666655997314,
            id: '184',
            index: 0,
            parentId: '2',
            title: 'dazidazi-在线打字练习网站-提高打字速度-打字测试-标准指法',
            url: 'https://dazidazi.com/',
            key: '0-0-1-0',
          },
          {
            dateAdded: 1671342227828,
            id: '185',
            index: 1,
            parentId: '2',
            title: 'typing-cn',
            url: 'https://barneyzhao.gitee.io/typing-cn/',
            key: '0-0-1-1',
          },
          {
            dateAdded: 1676192241380,
            id: '217',
            index: 2,
            parentId: '2',
            title: 'Qwerty Learner',
            url: 'https://qwerty.kaiyi.cool/',
            key: '0-0-1-2',
          },
          {
            dateAdded: 1686626829336,
            id: '618',
            index: 3,
            parentId: '2',
            title: "TechFen's Blog",
            url: 'https://www.techfens.com/',
            key: '0-0-1-3',
          },
        ],
        dateAdded: 1661418109722,
        id: '2',
        index: 1,
        parentId: '0',
        title: '其他收藏夹',
        key: '0-0-1',
      },
      {
        children: [
          {
            dateAdded: 1627788961463,
            id: '8',
            index: 0,
            parentId: '3',
            title: '深圳市嘉立创科技发展有限公司-专业PCB厂家-PCB打样-PCB报价',
            url: 'https://m.jlc.com/',
            key: '0-0-2-0',
          },
          {
            dateAdded: 1627830448874,
            id: '9',
            index: 1,
            parentId: '3',
            title: '国产立创EDA - 一个用心为中国人定制的电路板开发平台',
            url: 'https://lceda.cn/',
            key: '0-0-2-1',
          },
          {
            dateAdded: 1628143515187,
            id: '10',
            index: 2,
            parentId: '3',
            title: '快猫短视频',
            url: 'https://km4m4.xyz/',
            key: '0-0-2-2',
          },
          {
            dateAdded: 1628814917409,
            id: '11',
            index: 3,
            parentId: '3',
            title: 'PCB打样_pcb线路板打样_pcb厂家-猎板极速PCB打样智慧工厂',
            url: 'https://www.pcbhunt.com/#/pages/quote/index',
            key: '0-0-2-3',
          },
          {
            dateAdded: 1628949332712,
            id: '12',
            index: 4,
            parentId: '3',
            title: '极客迷-DIY学习与分享社区',
            url: 'http://www.geekfans.com/touch/?mobile=2',
            key: '0-0-2-4',
          },
          {
            dateAdded: 1629198484531,
            id: '13',
            index: 5,
            parentId: '3',
            title: '极客迷网—DIY学习与分享社区',
            url: 'http://www.geekfans.com/',
            key: '0-0-2-5',
          },
          {
            dateAdded: 1633476478139,
            id: '14',
            index: 6,
            parentId: '3',
            title: '科创 - 发展科技爱好，倡导科学理性',
            url: 'https://www.kechuang.org/',
            key: '0-0-2-6',
          },
          {
            dateAdded: 1629200439659,
            id: '15',
            index: 7,
            parentId: '3',
            title: '淘宝网 - 淘！我喜欢',
            url: 'https://www.taobao.com/?spm=a230r.1.1581860521.1.66af715aRvty2q',
            key: '0-0-2-7',
          },
          {
            dateAdded: 1643954689101,
            id: '186',
            index: 8,
            parentId: '3',
            title: 'OSHWHub - 立创EDA开源硬件平台',
            url: 'https://oshwhub.com/OSHWHub',
            key: '0-0-2-8',
          },
          {
            dateAdded: 1655472600943,
            id: '187',
            index: 9,
            parentId: '3',
            title: 'Termux 高级终端安装使用配置教程 | 国光',
            url: 'https://www.sqlsec.com/2018/05/termux.html?from=groupmessage',
            key: '0-0-2-9',
          },
          {
            dateAdded: 1656057992286,
            id: '188',
            index: 10,
            parentId: '3',
            title: '百位学长学姐填报锦囊',
            url: 'https://www.bilibili.com/blackboard/activity-wnOj1Wog37.html?i_transfer_match=fb73d23d-e245-4dd8-93b3-47306458f642#/',
            key: '0-0-2-10',
          },
          {
            dateAdded: 1656065879304,
            id: '189',
            index: 11,
            parentId: '3',
            title: '大学生活质量指北',
            url: 'https://colleges.chat/',
            key: '0-0-2-11',
          },
          {
            dateAdded: 1657954545666,
            id: '190',
            index: 12,
            parentId: '3',
            title: '欢迎使用 Colaboratory - Colaboratory',
            url: 'https://colab.research.google.com/#scrollTo=OwuxHmxllTwN',
            key: '0-0-2-12',
          },
          {
            dateAdded: 1673156562516,
            id: '191',
            index: 13,
            parentId: '3',
            title: 'Alibb影视',
            url: 'http://aliyongjiu.com/',
            key: '0-0-2-13',
          },
        ],
        dateAdded: 1661418109722,
        id: '3',
        index: 2,
        parentId: '0',
        title: '移动收藏夹',
        key: '0-0-2',
      },
      {
        children: [],
        dateAdded: 1700784344062,
        id: '669',
        index: 5,
        parentId: '0',
        title: '已删除收藏夹',
        key: '0-0-3',
      },
    ],
    dateAdded: 1700784343801,
    id: '0',
    title: '',
    key: '0-0',
  },
]

// @ts-ignore
export function addKeyProperty(data, key = '') {
  // @ts-ignore
  return data.map((item, index) => {
    const itemKey = key ? `${key}-${index}` : `${index}`
    const newItem = { ...item, key: itemKey }
    if (item.children) {
      newItem.children = addKeyProperty(item.children, itemKey)
    }
    return newItem
  })
}

export default favorites
